#!/bin/bash


nanoraw=SRR5665597
shortraw=ERR1023775
nthreads=64

fastq-dump $nanoraw --split-3
fastq-dump $shortraw --split-3

fastqc $shortraw* #run fastqc for both forward (1) and reverse (2) reads files

NanoPlot --fastq $nanoraw.fastq --outdir Nanoplots

#shortreads only
unicycler  -1 $shortread\_1.fastq -2 $shortread\_2.fastq -o unicycler_short --threads $nthreads


#longreads only
unicycler -l $nanoraw.fastq -o unicycler_hybrid --threads $nthreads

#Hybrid Assembly 
unicycler -1 $shortread\_1.fastq -2 $shortread\_2.fastq -l $nanoraw.fastq -o unicycler_hybrid --threads $nthreads


exit
