#!/bin/bash
# 11/1/2019
# This is a script to perform Unicycler assemblies of bacterial genomes.

nanoraw=SRR7908033
shortraw=ERR2102163
nthreads=12

fastq-dump $nanoraw --split-3
fastq-dump $shortraw --split-3

fastqc $shortraw* #run fastqc for both forward (1) and reverse (2) reads files

NanoPlot --fastq $nanoraw.fastq --outdir Nanoplots

#shortreads only
unicycler  -1 $shortraw\_1.fastq -2 $shortraw\_2.fastq -o unicycler_short --threads $nthreads


#longreads only
unicycler -l $nanoraw.fastq -o unicycler_long --threads $nthreads

#Hybrid Assembly 
unicycler -1 $shortraw\_1.fastq -2 $shortraw\_2.fastq -l $nanoraw.fastq -o unicycler_hybrid --threads $nthreads


exit
